const banlist = {
    banned: [],
    limited: [
        "Left Arm of the Forbidden One",
        "Left Leg of the Forbidden One",
        "Right Arm of the Forbidden One",
        "Right Leg of the Forbidden One",
        "Breaker the Magical Warrior",
        "Cyber Jar",
        "Exiled Force",
        "Exodia the Forbidden One",
        "Fiber Jar",
        "Injection Fairy Lily",
        "Jinzo",
        "Magical Scientist",
        "Morphing Jar",
        "Reflect Bounder",
        "Sangan",
        "Sinister Serpent",
        "Vampire Lord",
        "Witch of the Black Forest",
        "Tribe-Infecting Virus",
        "Twin-Headed Behemoth",
        "Yata-Garasu",
        "Card Destruction",
        "Change of Heart",
        "Confiscation",
        "Dark Hole",
        "Delinquent Duo",
        "Graceful Charity",
        "Heavy Storm",
        "Mage Power",
        "Mirage of Nightmare",
        "Monster Reborn",
        "Painful Choice",
        "Pot of Greed",
        "Premature Burial",
        "Raigeki",
        "Snatch Steal",
        "Swords of Revealing Light",
        "The Forceful Sentry",
        "United We Stand",
        "Upstart Goblin",
        "Butterfly Dagger Elma",
        "Harpie's Feather Duster",
        "Call of the Haunted",
        "Ceasefire",
        "Imperial Order",
        "Magic Cylinder",
        "Mirror Force",
        "Reckless Greed",
        "Ring of Destruction"
    ],
    semilimited: [
        "Marauding Captain",
        "Morphing Jar #2",
        "Creature Swap",
        "Nobleman of Crossout",
        "Reinforcement of the Army",
        "Last Turn"
    ]
};

export default banlist;