const banlist = {
	banned: [
		"Cyber Jar",
		"Fiber Jar",
		"Injection Fairy Lily",
		"Yata-Garasu",
		"Change of Heart",
		"Delinquent Duo",
		"Harpie's Feather Duster",
		"Painful Choice",
		"Raigeki",
		"Imperial Order",
	],
	limited: [
		"Black Luster Soldier - Envoy of the Beginning",
		"Breaker the Magical Warrior",
		"Chaos Emperor Dragon - Envoy of the End",
		"Dark Magician of Chaos",
		"Exiled Force",
		"Exodia the Forbidden One",
		"Jinzo",
		"Magical Scientist",
		"Reflect Bounder",
		"Sangan",
		"Sinister Serpent",
		"Tribe-Infecting Virus",
		"Twin-Headed Behemoth",
		"Vampire Lord",
		"Witch of the Black Forest",
		"Left Arm of the Forbidden One",
		"Left Leg of the Forbidden One",
		"Right Arm of the Forbidden One",
		"Right Leg of the Forbidden One",
		"Butterfly Dagger - Elma",
		"Card Destruction",
		"Confiscation",
		"Dark Hole",
		"Graceful Charity",
		"Heavy Storm",
		"Mage Power",
		"Mirage of Nightmare",
		"Monster Reborn",
		"Pot of Greed",
		"Premature Burial",
		"Snatch Steal",
		"Swords of Revealing Light",
		"The Forceful Sentry",
		"United We Stand",
		"Upstart Goblin",
		"Call of the Haunted",
		"Ceasefire",
		"Exchange of the Spirit",
		"Magic Cylinder",
		"Mirror Force",
		"Reckless Greed",
		"Ring of Destruction",
	],
	semilimited: [
		"Makyura the Destructor",
		"Manticore of Darkness",
		"Morphing Jar",
		"Creature Swap",
		"Nobleman of Crossout",
		"Reinforcement of the Army",
		"Last Turn",
	],
};

export default banlist;
