const banlist = {
	banned: [],
	limited: [
		"Cyber Jar",
		"Exiled Force",
		"Exodia the Forbidden One",
		"Fiber Jar",
		"Injection Fairy Lily",
		"Jinzo",
		"Makyura the Destructor",
		"Morphing Jar",
		"Slate Warrior",
		"Twin-Headed Behemoth",
		"Witch of the Black Forest",
		"Yata-Garasu",
		"Left Arm of the Forbidden One",
		"Left Leg of the Forbidden One",
		"Right Arm of the Forbidden One",
		"Right Leg of the Forbidden One",
		"Card Destruction",
		"Change of Heart",
		"Confiscation",
		"Dark Hole",
		"Delinquent Duo",
		"Harpie's Feather Duster",
		"Heavy Storm",
		"Limiter Removal",
		"Mage Power",
		"Monster Reborn",
		"Painful Choice",
		"Pot of Greed",
		"Premature Burial",
		"Raigeki",
		"Snatch Steal",
		"Swords of Revealing Light",
		"The Forceful Sentry",
		"United We Stand",
		"Upstart Goblin",
		"Call of the Haunted",
		"Ceasefire",
		"Exchange of the Spirit",
		"Imperial Order",
		"Magic Cylinder",
		"Mirror Force",
		"Reckless Greed",
		"Ring of Destruction",
	],
	semilimited: [
		"Guardian Sphinx",
		"Marauding Captain",
		"Morphing Jar #2",
		"Sangan",
		"Graceful Charity",
		"Nobleman of Crossout",
		"Reinforcement of the Army",
		"Riryoku",
		"Backup Soldier",
		"Last Turn",
	],
};

export default banlist;
